### PR TITLE
ENH: Refactor to use libvcs

### PR DESCRIPTION
**Pull request by jcfr**
This is an attempt to update the project to depend on the newly introduced project `libvcs`.

See https://github.com/tony/vcspull/pull/38#issuecomment-227085360

### CODE REVIEW

**Comment by jcfr** [comment]
Simply updating the requirements and using `create_repo_from_pip_url` instead of `create_repo` leads to the following error:

```
$ ./extensions-index-checkout.py --filter=SlicerIGT ../ExtensionsIndex ../ExtensionsSource
|None| (None)  extensions_source_dir is [/home/jcfr/Projects/sandbox/ExtensionsSource]
|None| (None)  extensions_index_dir is [/home/jcfr/Projects/sandbox/ExtensionsIndex]
Traceback (most recent call last):
  File "./extensions-index-checkout.py", line 108, in <module>
    duration, result = timecall(repo.update_repo)()
  File "./extensions-index-checkout.py", line 29, in wrapper
    result = method(*args, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/git.py", line 173, in update_repo
    print_stdout_on_progress_end=False)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/base.py", line 200, in run
    *args, **kwargs
TypeError: run() got an unexpected keyword argument 'print_stdout_on_progress_end'
```

Questions:
- In order to have every git command displayed, how should the new [libvcs/git.py](https://github.com/tony/libvcs/blob/master/libvcs/git.py) be fixed ? 

Desired output: 

```
$ ./extensions-index-checkout.py ../ExtensionsSource ../ExtensionsIndex
|None| (None)  extensions_source_dir is [/home/jcfr/Projects/sandbox/ExtensionsSource]
|None| (None)  extensions_index_dir is [/home/jcfr/Projects/sandbox/ExtensionsIndex]
|SobolevSegmenter| (git)  Cloning.
|SobolevSegmenter| (git)  'git' 'clone' '--progress' 'git://github.com/anry123/SobolevSegmenter.git' '/home/jcfr/Projects/sandbox/ExtensionsSource/SobolevSegmenter'
Cloning into '/home/jcfr/Projects/sandbox/ExtensionsSource/SobolevSegmenter'...
remote: Counting objects: 64, done.        
remote: Total 64 (delta 0), reused 0 (delta 0), pack-reused 64        
ing objects: 100% (64/64), 41.61 KiB | 0 bytes/s, done.
Resolving deltas: 100% (18/18), done.
.. done. connectivity.
|SobolevSegmenter| (git)  Initializing submodules.                                                                     
|SobolevSegmenter| (git)  'git' 'submodule' 'init'
|SobolevSegmenter| (git)  'git' 'submodule' 'update' '--recursive' '--init'
|SobolevSegmenter| (git)  Updating to 'a67800a'.
|SobolevSegmenter| (git)  'git' 'rev-list' '--max-count=1' 'HEAD'
|SobolevSegmenter| (git)  'git' 'show-ref' 'a67800a'
|SobolevSegmenter| (git)  'git' 'rev-list' '--max-count=1' 'a67800a'
|SobolevSegmenter| (git)  Already up-to-date.
|SobolevSegmenter| (git)  Elapsed time: 0.26s

|DiceComputation| (git)  Cloning.
|DiceComputation| (git)  'git' 'clone' '--progress' 'git://github.com/lchauvin/DiceComputation.git' '/home/jcfr/Projects/sandbox/ExtensionsSource/DiceComputation'
Cloning into '/home/jcfr/Projects/sandbox/ExtensionsSource/DiceComputation'...
remote: Counting objects: 268, done.        
remote: Total 268 (delta 0), reused 0 (delta 0), pack-reused 268        
Receiving objects: 100% (268/268), 65.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (155/155), done.
Checking connectivity... done.
|DiceComputation| (git)  Initializing submodules.                                                              
|DiceComputation| (git)  'git' 'submodule' 'init'
|DiceComputation| (git)  'git' 'submodule' 'update' '--recursive' '--init'
|DiceComputation| (git)  Updating to '11e62e2337252aa0214189c17489a89d5ad4d9ef'.
|DiceComputation| (git)  'git' 'rev-list' '--max-count=1' 'HEAD'
|DiceComputation| (git)  'git' 'show-ref' '11e62e2337252aa0214189c17489a89d5ad4d9ef'
|DiceComputation| (git)  'git' 'rev-list' '--max-count=1' '11e62e2337252aa0214189c17489a89d5ad4d9ef'
|DiceComputation| (git)  Already up-to-date.
|DiceComputation| (git)  Elapsed time: 0.22s
[...]
```

**Comment by tony** [comment]
I released a 0.1.4 that should fix the error. There isn't test coverage inside of that area yet (https://github.com/tony/libvcs/issues/3)

For the latest libvcs, the argument signature of creating repos from pip url's changed:

``` diff
diff --git a/extensions-index-checkout.py b/extensions-index-checkout.py
index 2c1e8ec..dc9bd64 100755
--- a/extensions-index-checkout.py
+++ b/extensions-index-checkout.py
@@ -104,7 +104,7 @@ if __name__ == '__main__':
         for param_name in ['username', 'password']:
             if 'svn' + param_name in metadata:
                 kwargs['svn_' + param_name] = metadata['svn' + param_name]
-        repo = create_repo(url=url, parent_dir=extensions_source_dir, name=extension_name, **kwargs)
+        repo = create_repo(pip_url=url, repo_dir=os.path.join(extensions_source_dir, extension_name), **kwargs)
         duration, result = timecall(repo.update_repo)()
         repo.info("Elapsed time: {:.2f}s\n".format(duration))
         if not elapsed_time_collected:
```

Here are the latest signatures / API infos http://libvcs.readthedocs.io/en/latest/api.html (up to date with master on gh)

If you update to libvcs 0.1.4, does that help?

**Comment by tony** [comment]
The area I'm working on next is ironing out stdout/stderr consistently everywhere and maybe deprecating `run_buffered` completely (https://github.com/tony/libvcs/issues/6).  The `run_buffered` checkered throughout update is inherited from vcspull, where commands like git pull/git fetch that show update progress to CLI via streaming to stderr could pass through. That isn't as relevant in a library where that information may not be valuable/interesting since this is just a lib.

**Comment by jcfr** [comment]
>  released a 0.1.4 that should fix the error.

Great :+1:  I will give a try.

(( Ps: As a side note, I noticed that you rewrote the history of libvcs. As a side effect, the tag like v0.1.0 and v0.1.1 got lost. Not a major problem .. just wondering if this was the intended effect ))

> git pull/git fetch that show update progress

I think having the option to optionally show progress within `libvcs` makes sense. For potentially long running command like `git clone`, `git fetch`, it is relevant to provide feedback to the user in an application specific way.

**Comment by jcfr** [comment]
@tony After updating the latest libvcs, look like there are still issues.

``` bash
$ ./extensions-index-checkout.py --filter=SlicerIGT ../ExtensionsIndex ../ExtensionsSource
|None| (None)  extensions_source_dir is [/home/jcfr/Projects/sandbox/ExtensionsSource]
|None| (None)  extensions_index_dir is [/home/jcfr/Projects/sandbox/ExtensionsIndex]
Traceback (most recent call last):
  File "./extensions-index-checkout.py", line 107, in <module>
    repo = create_repo(url, parent_dir=extensions_source_dir, name=extension_name, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/shortcuts.py", line 74, in create_repo_from_pip_url
    return GitRepo.from_pip_url(pip_url, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/base.py", line 116, in from_pip_url
    self = cls(url=url, rev=rev, *args, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/git.py", line 74, in __init__
    BaseRepo.__init__(self, url, **kwargs)
TypeError: __init__() takes at least 3 arguments (2 given)
```

I attempted to fix the issue, applying the following patch:

``` diff
diff --git a/libvcs/git.py b/libvcs/git.py
index 84f827f..6d20a52 100644
--- a/libvcs/git.py
+++ b/libvcs/git.py
@@ -71,7 +71,16 @@ class GitRepo(BaseRepo):
             self.git_submodules = []
         if 'tls_verify' not in kwargs:
             self.tls_verify = False
-        BaseRepo.__init__(self, url, **kwargs)
+
+        parent_dir = kwargs['parent_dir']
+        del kwargs['parent_dir']
+
+        name = kwargs['name']
+        del kwargs['name']
+
+        repo_dir = os.path.join(parent_dir, name)
+
+        BaseRepo.__init__(self, url, repo_dir, **kwargs)

         self.remotes = remotes
```

but then, I got:

```
$ ./extensions-index-checkout.py --filter=SlicerIGT ../ExtensionsIndex ../ExtensionsSource
|None| (None)  extensions_source_dir is [/home/jcfr/Projects/sandbox/ExtensionsSource]
|None| (None)  extensions_index_dir is [/home/jcfr/Projects/sandbox/ExtensionsIndex]
Traceback (most recent call last):
  File "./extensions-index-checkout.py", line 107, in <module>
    repo = create_repo(url, parent_dir=extensions_source_dir, name=extension_name, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/shortcuts.py", line 74, in create_repo_from_pip_url
    return GitRepo.from_pip_url(pip_url, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/base.py", line 116, in from_pip_url
    self = cls(url=url, rev=rev, *args, **kwargs)
  File "/home/jcfr/Projects/sandbox/libvcs/libvcs/git.py", line 74, in __init__
    BaseRepo.__init__(self, url, **kwargs)
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by jcfr** [comment]
@tony  Here is an idea: 

Re-factorying `vcspull` into `vcslib` makes sense. That said, waiting we stabilize the API and its requirements, what do you think of (for now) keeping the re-factoring within `vcspull`.

That would allow to incrementally add tests, introduce the new API, and minimize major breakage.

Let me know what you think ?

**Comment by tony** [comment]
Taking a look

**Comment by tony** [comment]
What workflow do you have when editing python?

Have you tried to clone `libvcs` and `pip install -e` it?  That way you can work off a local version and still maneuver around it as a git repo.

``` sh
cd ~/Projects
git clone https://github.com/tony/libvcs.git
cd libvcs
git remote add jcfr git@github.com:jcfr/libvcs.git

cd ~/Projects
git clone git@github.com:jcfr/pys4ext.git
cd pys4ext
virtualenv .venv  # create virtualenv (you may want to add `/.venv`` to global .gitignore

# anytime you want to be in the environment
source .venv/bin/activate

# install libvcs via --editable
pip install -U -e ~/Projects/libvcs
```

Now you can do local edits to ~/Projects/libvcs, do git stuff between your fork and origin, and pys4ext will always use the latest changes from within ~/Projects/libvcs.

**Comment by jcfr** [comment]
> workflow do you have when editing python

similar to what you described expect I use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)

Thanks for the PR :+1: 

Closing this one since it is superseded by #2

**Pull request closed without merging**
